import { 
  Character, 
  GameSkin, 
  GameTrail, 
  GameDeathEffect, 
  GameTheme, 
  GameSettings, 
  GameStats,
  DailyMission,
  AchievementItem,
  CustomCharacterConfig,
  CustomThemeConfig,
  PlayerUpgrades,
  CustomPaletteItem,
  CustomBackgroundItem,
  CustomAccessoryItem,
  CustomAuraItem,
  UpgradeDefinition
} from '../types';

import { NARRATOR_SPEED } from '../services/narratorConfig';

export const INITIAL_CHARACTERS: Character[] = [
  {
    id: 'neon_drop',
    name: 'NEON DROP',
    desc: 'Gota cibernética clássica com aura ciano cintilante.',
    price: 0,
    unlocked: true,
    primaryColor: '#00f2ff',
    glowColor: '#00a6ff',
    trailColor: 'rgba(0, 242, 255, 0.6)',
    particleType: 'cyan_glow',
    accentColor: '#00d9ff',
    rarity: 'COMMON',
  },
  {
    id: 'fire_drop',
    name: 'FIRE DROP',
    desc: 'Gota de plasma ardente com rastro de chamas incandescentes.',
    price: 250,
    unlocked: false,
    primaryColor: '#ff5500',
    glowColor: '#ff0044',
    trailColor: 'rgba(255, 85, 0, 0.7)',
    particleType: 'fire',
    accentColor: '#ffaa00',
    rarity: 'RARE',
  },
  {
    id: 'ice_drop',
    name: 'ICE DROP',
    desc: 'Estrutura glacial de cristal com faíscas congeladas.',
    price: 400,
    unlocked: false,
    primaryColor: '#00e5ff',
    glowColor: '#ffffff',
    trailColor: 'rgba(200, 245, 255, 0.7)',
    particleType: 'ice',
    accentColor: '#a5f3fc',
    rarity: 'RARE',
  },
  {
    id: 'gold_drop',
    name: 'GOLD DROP',
    desc: 'Reluzente gota de ouro maciço e puro luxo ostentação.',
    price: 600,
    unlocked: false,
    primaryColor: '#fbbf24',
    glowColor: '#f59e0b',
    trailColor: 'rgba(251, 191, 36, 0.9)',
    particleType: 'stardust',
    accentColor: '#fffbeb',
    rarity: 'EPIC',
  },
  {
    id: 'void_drop',
    name: 'VOID DROP',
    desc: 'Matéria escura que distorce a luz ao seu redor.',
    price: 800,
    unlocked: false,
    primaryColor: '#1e1b4b',
    glowColor: '#a855f7',
    trailColor: 'rgba(30, 27, 75, 0.9)',
    particleType: 'void_shadow',
    accentColor: '#c084fc',
    rarity: 'EPIC',
  },
  {
    id: 'toxic_drop',
    name: 'TOXIC DROP',
    desc: 'Fluido bio-tóxico radioativo com brilho verde fúria.',
    price: 1000,
    unlocked: false,
    primaryColor: '#22c55e',
    glowColor: '#10b981',
    trailColor: 'rgba(34, 197, 94, 0.8)',
    particleType: 'toxic_plasma',
    accentColor: '#86efac',
    rarity: 'EPIC',
  },
  {
    id: 'cyber_drop',
    name: 'CYBER DROP',
    desc: 'Entidade digital oscilando em matriz de dados neon.',
    price: 1200,
    unlocked: false,
    primaryColor: '#3b82f6',
    glowColor: '#06b6d4',
    trailColor: 'rgba(59, 130, 246, 0.8)',
    particleType: 'glitch_pixels',
    accentColor: '#93c5fd',
    rarity: 'LEGENDARY',
  },
  {
    id: 'galaxy_drop',
    name: 'GALAXY DROP',
    desc: 'Poeira estelar pulsando com cores infinitas da galáxia.',
    price: 1500,
    unlocked: false,
    primaryColor: '#f472b6',
    glowColor: '#8b5cf6',
    trailColor: 'rgba(244, 114, 182, 0.8)',
    particleType: 'stardust',
    accentColor: '#fef08a',
    rarity: 'LEGENDARY',
  },
  {
    id: 'glitch_drop',
    name: 'GLITCH DROP',
    desc: 'Distorção cromática instável de puro código corrompido.',
    price: 1800,
    unlocked: false,
    primaryColor: '#ec4899',
    glowColor: '#a855f7',
    trailColor: 'rgba(236, 72, 153, 0.9)',
    particleType: 'glitch_pixels',
    accentColor: '#00f2ff',
    rarity: 'LEGENDARY',
  },
  {
    id: 'shadow_drop',
    name: 'SHADOW DROP',
    desc: 'Sombra abissal lendária das profundezas da fenda.',
    price: 2000,
    unlocked: false,
    primaryColor: '#020617',
    glowColor: '#6366f1',
    trailColor: 'rgba(99, 102, 241, 0.9)',
    particleType: 'void_shadow',
    accentColor: '#cbd5e1',
    rarity: 'LEGENDARY',
  },
  {
    id: 'nox',
    name: 'NOX',
    desc: 'Núcleo ciberpunc clássico.',
    price: 0,
    unlocked: true,
    primaryColor: '#00f2ff',
    glowColor: '#00a6ff',
    trailColor: 'rgba(0, 242, 255, 0.6)',
    particleType: 'cyan_glow',
    accentColor: '#00d9ff',
    rarity: 'COMMON',
  },
  {
    id: 'blaze',
    name: 'BLAZE',
    desc: 'Energia de fogo ardente.',
    price: 250,
    unlocked: false,
    primaryColor: '#ff5500',
    glowColor: '#ff0044',
    trailColor: 'rgba(255, 85, 0, 0.7)',
    particleType: 'fire',
    accentColor: '#ffaa00',
    rarity: 'RARE',
  },
  {
    id: 'frost',
    name: 'FROST',
    desc: 'Estrutura glacial com partículas congeladas.',
    price: 500,
    unlocked: false,
    primaryColor: '#00e5ff',
    glowColor: '#ffffff',
    trailColor: 'rgba(200, 245, 255, 0.7)',
    particleType: 'ice',
    accentColor: '#a5f3fc',
    rarity: 'RARE',
  },
  {
    id: 'volt',
    name: 'VOLT',
    desc: 'Esfera bioelétrica disparando arcos de voltagem.',
    price: 750,
    unlocked: false,
    primaryColor: '#ffee00',
    glowColor: '#00e1ff',
    trailColor: 'rgba(255, 238, 0, 0.8)',
    particleType: 'electric',
    accentColor: '#fef08a',
    rarity: 'RARE',
  },
  {
    id: 'glitch',
    name: 'GLITCH',
    desc: 'Entidade cibernética com pulsos digitais oscilantes.',
    price: 1000,
    unlocked: false,
    primaryColor: '#a855f7',
    glowColor: '#00f2ff',
    trailColor: 'rgba(168, 85, 247, 0.8)',
    particleType: 'glitch_pixels',
    accentColor: '#ec4899',
    rarity: 'EPIC',
  },
  {
    id: 'shadow',
    name: 'SHADOW',
    desc: 'Matéria escura que distorce a luz ao seu redor.',
    price: 1500,
    unlocked: false,
    primaryColor: '#1e1b4b',
    glowColor: '#a855f7',
    trailColor: 'rgba(30, 27, 75, 0.9)',
    particleType: 'void_shadow',
    accentColor: '#c084fc',
    rarity: 'EPIC',
  },
  {
    id: 'cosmo',
    name: 'COSMO',
    desc: 'Fragmento estelar pulsando com poeira cósmica.',
    price: 2000,
    unlocked: false,
    primaryColor: '#f472b6',
    glowColor: '#3b82f6',
    trailColor: 'rgba(244, 114, 182, 0.8)',
    particleType: 'stardust',
    accentColor: '#fef08a',
    rarity: 'LEGENDARY',
  },
  // 7 Novos Personagens Lendários Viciantes
  {
    id: 'quantum_drop',
    name: 'QUANTUM DROP',
    desc: 'Partícula em superposição com aura violeta e ciano estroboscópica.',
    price: 1200,
    unlocked: false,
    primaryColor: '#8b5cf6',
    glowColor: '#00f2ff',
    trailColor: 'rgba(139, 92, 246, 0.85)',
    particleType: 'quantum',
    accentColor: '#c4b5fd',
    rarity: 'LEGENDARY',
  },
  {
    id: 'solar_flare',
    name: 'SOLAR FLARE',
    desc: 'Fusão nuclear viva emanando radiação solar dourada e labaredas.',
    price: 1400,
    unlocked: false,
    primaryColor: '#f59e0b',
    glowColor: '#ef4444',
    trailColor: 'rgba(245, 158, 11, 0.9)',
    particleType: 'fire',
    accentColor: '#fef08a',
    rarity: 'LEGENDARY',
  },
  {
    id: 'prism_diamond',
    name: 'PRISM DIAMOND',
    desc: 'Diamante hiperbólico refratando luz caleidoscópica infinita.',
    price: 1600,
    unlocked: false,
    primaryColor: '#38bdf8',
    glowColor: '#f472b6',
    trailColor: 'rgba(56, 189, 248, 0.9)',
    particleType: 'prism',
    accentColor: '#ffffff',
    rarity: 'LEGENDARY',
  },
  {
    id: 'nebula_king',
    name: 'NEBULA KING',
    desc: 'Monarca do cosmos vestindo véu estelar de gás interestelar.',
    price: 1800,
    unlocked: false,
    primaryColor: '#6366f1',
    glowColor: '#a855f7',
    trailColor: 'rgba(99, 102, 241, 0.9)',
    particleType: 'stardust',
    accentColor: '#f472b6',
    rarity: 'LEGENDARY',
  },
  {
    id: 'cyber_phantom',
    name: 'CYBER PHANTOM',
    desc: 'Espectro fantasmagórico que viaja na velocidade dos elétrons.',
    price: 2000,
    unlocked: false,
    primaryColor: '#10b981',
    glowColor: '#00f2ff',
    trailColor: 'rgba(16, 185, 129, 0.85)',
    particleType: 'glitch_pixels',
    accentColor: '#6ee7b7',
    rarity: 'LEGENDARY',
  },
  {
    id: 'bio_hazard',
    name: 'BIO HAZARD',
    desc: 'Isótopo radioativo verde-ácido emanando ondas de energia atômica.',
    price: 2200,
    unlocked: false,
    primaryColor: '#84cc16',
    glowColor: '#22c55e',
    trailColor: 'rgba(132, 204, 22, 0.9)',
    particleType: 'toxic_plasma',
    accentColor: '#d9f99d',
    rarity: 'LEGENDARY',
  },
  {
    id: 'golden_god',
    name: 'GOLDEN GOD',
    desc: 'A divindade suprema do Wall Drop em ouro puro esculpido no éter.',
    price: 3000,
    unlocked: false,
    primaryColor: '#fbbf24',
    glowColor: '#ffffff',
    trailColor: 'rgba(251, 191, 36, 0.95)',
    particleType: 'gold_celestial',
    accentColor: '#fffbeb',
    rarity: 'LEGENDARY',
  },
  {
    id: 'mystery',
    name: 'MYSTERY',
    desc: 'Lenda secreta! Desbloqueie fazendo Combo x30 ou 1.000 pontos.',
    price: 0,
    unlocked: false,
    primaryColor: '#fbbf24',
    glowColor: '#f59e0b',
    trailColor: 'rgba(251, 191, 36, 0.9)',
    particleType: 'mystery_aura',
    accentColor: '#fef08a',
    isSecret: true,
    rarity: 'LEGENDARY',
  },
];

export const INITIAL_SKINS: GameSkin[] = [
  {
    id: 'skin_neon',
    name: 'NEON',
    desc: 'Aparência ciberpunc clássica com iluminação sutil.',
    price: 0,
    unlocked: true,
    primaryColor: '#00f2ff',
    glowColor: '#3b82f6',
    accentColor: '#22d3ee',
    rarity: 'COMMON',
  },
  {
    id: 'skin_fire',
    name: 'CHAMA ARDENTE',
    desc: 'Glow abrasador de lava em fusão.',
    price: 300,
    unlocked: false,
    primaryColor: '#ef4444',
    glowColor: '#f97316',
    accentColor: '#fde047',
    rarity: 'RARE',
  },
  {
    id: 'skin_ice',
    name: 'AURORA GLACIAL',
    desc: 'Brilho criogênico de cristal congelado.',
    price: 600,
    unlocked: false,
    primaryColor: '#38bdf8',
    glowColor: '#06b6d4',
    accentColor: '#e0f2fe',
    rarity: 'RARE',
  },
  {
    id: 'skin_gold',
    name: 'OURO LENDÁRIO',
    desc: 'Revestimento reluzente de ouro maciço.',
    price: 1000,
    unlocked: false,
    primaryColor: '#fbbf24',
    glowColor: '#f59e0b',
    accentColor: '#fffbeb',
    rarity: 'EPIC',
  },
  {
    id: 'skin_glitch',
    name: 'CIBER GLITCH',
    desc: 'Sombra cromática instável com artefatos de fita.',
    price: 1500,
    unlocked: false,
    primaryColor: '#ec4899',
    glowColor: '#a855f7',
    accentColor: '#00f2ff',
    rarity: 'LEGENDARY',
  },
  {
    id: 'skin_shadow',
    name: 'NOITE ABISSAL',
    desc: 'Aura escura impenetrável das profundezas.',
    price: 2000,
    unlocked: false,
    primaryColor: '#0f172a',
    glowColor: '#6366f1',
    accentColor: '#818cf8',
    rarity: 'LEGENDARY',
  },
  // SKINS POR EMOJI
  {
    id: 'skin_clown',
    name: 'PALHAÇO',
    desc: 'O coringa do reflexo! Risada ácida e esquivas cômicas.',
    price: 180,
    unlocked: false,
    primaryColor: '#ef4444',
    glowColor: '#f59e0b',
    accentColor: '#ffffff',
    emoji: '🤡',
    rarity: 'COMMON',
  },
  {
    id: 'skin_cat',
    name: 'GATO SURPRESO',
    desc: 'Sete vidas de puro reflexo felino e pânico veloz.',
    price: 250,
    unlocked: false,
    primaryColor: '#f97316',
    glowColor: '#fbbf24',
    accentColor: '#fef08a',
    emoji: '🐱',
    rarity: 'RARE',
  },
  {
    id: 'skin_alien',
    name: 'ET ALIENÍGENA',
    desc: 'Consciência extraterrestre que dobra a física do corredor.',
    price: 450,
    unlocked: false,
    primaryColor: '#22c55e',
    glowColor: '#10b981',
    accentColor: '#a7f3d0',
    emoji: '👽',
    rarity: 'RARE',
  },
  {
    id: 'skin_robot',
    name: 'CYBER BOT',
    desc: 'Processador quântico programado para zero colisões.',
    price: 600,
    unlocked: false,
    primaryColor: '#38bdf8',
    glowColor: '#6366f1',
    accentColor: '#e0f2fe',
    emoji: '🤖',
    rarity: 'RARE',
  },
  {
    id: 'skin_gigachad',
    name: 'GIGACHAD',
    desc: 'Mandíbula de pedra inabalável que intimida os obstáculos.',
    price: 800,
    unlocked: false,
    primaryColor: '#94a3b8',
    glowColor: '#f59e0b',
    accentColor: '#ffffff',
    emoji: '🗿',
    rarity: 'EPIC',
  },
  {
    id: 'skin_fire_emoji',
    name: 'FOGO SELVAGEM',
    desc: 'Combustão viva com calor nuclear que frita a fenda.',
    price: 950,
    unlocked: false,
    primaryColor: '#f97316',
    glowColor: '#ef4444',
    accentColor: '#fde047',
    emoji: '🔥',
    rarity: 'EPIC',
  },
  {
    id: 'skin_lion',
    name: 'LEÃO ALFA',
    desc: 'O rei da selva dos reflexos com rugido magnético.',
    price: 1100,
    unlocked: false,
    primaryColor: '#f59e0b',
    glowColor: '#d97706',
    accentColor: '#fef3c7',
    emoji: '🦁',
    rarity: 'EPIC',
  },
  {
    id: 'skin_lightning',
    name: 'RAIO QUÂNTICO',
    desc: 'Velocidade da luz com descarga de alta voltagem.',
    price: 1300,
    unlocked: false,
    primaryColor: '#eab308',
    glowColor: '#00f2ff',
    accentColor: '#ffffff',
    emoji: '⚡',
    rarity: 'LEGENDARY',
  },
  {
    id: 'skin_rocket',
    name: 'FOGUETE ESPACIAL',
    desc: 'Propulsão orbital com velocidade de escape supersônica.',
    price: 1450,
    unlocked: false,
    primaryColor: '#ef4444',
    glowColor: '#38bdf8',
    accentColor: '#ffffff',
    emoji: '🚀',
    rarity: 'LEGENDARY',
  },
  {
    id: 'skin_unicorn',
    name: 'UNICÓRNIO',
    desc: 'Magia prismática multicolorida que desafia a gravidade.',
    price: 1600,
    unlocked: false,
    primaryColor: '#ec4899',
    glowColor: '#a855f7',
    accentColor: '#fbcfe8',
    emoji: '🦄',
    rarity: 'LEGENDARY',
  },
  {
    id: 'skin_skull',
    name: 'CAVEIRA ABISSAL',
    desc: 'Presença sombria que ri na cara da morte a cada desvio.',
    price: 1800,
    unlocked: false,
    primaryColor: '#0f172a',
    glowColor: '#dc2626',
    accentColor: '#fca5a5',
    emoji: '💀',
    rarity: 'LEGENDARY',
  },
  {
    id: 'skin_king',
    name: 'REI SUPREMO',
    desc: 'A realeza absoluta com manto dourado e coroa imperial.',
    price: 2200,
    unlocked: false,
    primaryColor: '#fbbf24',
    glowColor: '#f59e0b',
    accentColor: '#ffffff',
    emoji: '👑',
    rarity: 'LEGENDARY',
  },
];

export const INITIAL_TRAILS: GameTrail[] = [
  {
    id: 'cyan_trail',
    name: 'CYAN TRAIL',
    desc: 'Rastro suave de plasma pulsante ciano.',
    price: 0,
    unlocked: true,
    particleType: 'cyan_glow',
    color: '#00f2ff',
    rarity: 'COMMON',
  },
  {
    id: 'magenta_trail',
    name: 'MAGENTA TRAIL',
    desc: 'Aura vibrante magenta e rosa choque.',
    price: 200,
    unlocked: false,
    particleType: 'cyan_glow',
    color: '#ec4899',
    rarity: 'COMMON',
  },
  {
    id: 'fire_trail',
    name: 'FIRE TRAIL',
    desc: 'Cauda flamejante de brasas ardentes.',
    price: 350,
    unlocked: false,
    particleType: 'fire',
    color: '#ff5500',
    rarity: 'RARE',
  },
  {
    id: 'electric_trail',
    name: 'ELECTRIC TRAIL',
    desc: 'Faíscas bioelétricas de alta voltagem.',
    price: 500,
    unlocked: false,
    particleType: 'electric',
    color: '#ffee00',
    rarity: 'RARE',
  },
  {
    id: 'pixel_trail',
    name: 'PIXEL TRAIL',
    desc: 'Rastro retrô quadriculado em 8-bit.',
    price: 700,
    unlocked: false,
    particleType: 'glitch_pixels',
    color: '#a855f7',
    rarity: 'EPIC',
  },
  {
    id: 'rainbow_trail',
    name: 'RAINBOW TRAIL',
    desc: 'Espectro de cores dinâmico e brilhante.',
    price: 1000,
    unlocked: false,
    particleType: 'rainbow',
    color: '#f43f5e',
    rarity: 'LEGENDARY',
  },
  {
    id: 'glitch_trail',
    name: 'GLITCH TRAIL',
    desc: 'Artefatos de matriz corrompida.',
    price: 1200,
    unlocked: false,
    particleType: 'glitch_pixels',
    color: '#38bdf8',
    rarity: 'LEGENDARY',
  },
  {
    id: 'star_trail',
    name: 'STAR TRAIL',
    desc: 'Poeira estelar cintilante do espaço profundo.',
    price: 1500,
    unlocked: false,
    particleType: 'stardust',
    color: '#fbbf24',
    rarity: 'LEGENDARY',
  },
  {
    id: 'trail_energy',
    name: 'ENERGIA VITAL',
    desc: 'Rastro de energia azul ciano.',
    price: 0,
    unlocked: true,
    particleType: 'cyan_glow',
    color: '#00f2ff',
    rarity: 'COMMON',
  },
  {
    id: 'trail_fire',
    name: 'RASTRO DE FOGO',
    desc: 'Cauda flamejante.',
    price: 300,
    unlocked: false,
    particleType: 'fire',
    color: '#ff5500',
    rarity: 'RARE',
  },
  {
    id: 'trail_ice',
    name: 'CRISTAIS DE GELO',
    desc: 'Gelo azul cristalino.',
    price: 500,
    unlocked: false,
    particleType: 'ice',
    color: '#38bdf8',
    rarity: 'RARE',
  },
  {
    id: 'trail_stars',
    name: 'POEIRA DE ESTRELAS',
    desc: 'Estrelas cintilantes.',
    price: 800,
    unlocked: false,
    particleType: 'stardust',
    color: '#f472b6',
    rarity: 'EPIC',
  },
  {
    id: 'trail_glitch',
    name: 'RUÍDO DIGITAL',
    desc: 'Pixels em código.',
    price: 1200,
    unlocked: false,
    particleType: 'glitch_pixels',
    color: '#a855f7',
    rarity: 'LEGENDARY',
  },
  {
    id: 'trail_smoke',
    name: 'FUMAÇA SOMBRIA',
    desc: 'Névoa cinzenta.',
    price: 1500,
    unlocked: false,
    particleType: 'smoke',
    color: '#64748b',
    rarity: 'EPIC',
  },
  // 7 Novos Rastros Cósmicos
  {
    id: 'trail_supernova',
    name: 'SUPERNOVA',
    desc: 'Explosão contínua de fótons incandescentes estelares.',
    price: 1800,
    unlocked: false,
    particleType: 'stardust',
    color: '#f59e0b',
    rarity: 'LEGENDARY',
  },
  {
    id: 'trail_plasmastorm',
    name: 'TEMPESTADE DE PLASMA',
    desc: 'Arcos elétricos de plasma em fusão contínua.',
    price: 2000,
    unlocked: false,
    particleType: 'electric',
    color: '#06b6d4',
    rarity: 'LEGENDARY',
  },
  {
    id: 'trail_matrix',
    name: 'CÓDIGO MATRIX',
    desc: 'Chuva binária de glifos neon escorrendo no abismo.',
    price: 2200,
    unlocked: false,
    particleType: 'glitch_pixels',
    color: '#22c55e',
    rarity: 'LEGENDARY',
  },
  {
    id: 'trail_prism',
    name: 'ONDA PRISMÁTICA',
    desc: 'Refração espectral infinita que ilumina o caminho.',
    price: 2400,
    unlocked: false,
    particleType: 'rainbow',
    color: '#ec4899',
    rarity: 'LEGENDARY',
  },
  {
    id: 'trail_firestorm',
    name: 'TEMPESTADE DE FOGO',
    desc: 'Turbilhões de chamas vivas e labaredas cósmicas.',
    price: 2600,
    unlocked: false,
    particleType: 'fire',
    color: '#ef4444',
    rarity: 'LEGENDARY',
  },
  {
    id: 'trail_biohazard',
    name: 'RADIOATIVO BIO',
    desc: 'Esporos bio-químicos fluorescentes de alta radiação.',
    price: 2800,
    unlocked: false,
    particleType: 'cyan_glow',
    color: '#84cc16',
    rarity: 'LEGENDARY',
  },
  {
    id: 'trail_infinitygold',
    name: 'OURO INFINITO',
    desc: 'Aura suprema de lingotes de ouro celeste e diamantes.',
    price: 3500,
    unlocked: false,
    particleType: 'stardust',
    color: '#fbbf24',
    rarity: 'LEGENDARY',
  },
];

export const INITIAL_DEATH_EFFECTS: GameDeathEffect[] = [
  {
    id: 'neon_shatter',
    name: 'NEON SHATTER',
    desc: 'Shatter reluzente com faíscas neon e anéis de choque.',
    price: 0,
    unlocked: true,
    type: 'shatter',
    rarity: 'COMMON',
  },
  {
    id: 'pixel_explosion',
    name: 'PIXEL EXPLOSION',
    desc: 'Fragmentação em blocos 8-bit com explosão de energia.',
    price: 300,
    unlocked: false,
    type: 'pixels',
    rarity: 'RARE',
  },
  {
    id: 'glitch_crash',
    name: 'GLITCH CRASH',
    desc: 'Colapso de sistema com distorção cromática e artefatos.',
    price: 500,
    unlocked: false,
    type: 'glitch',
    rarity: 'EPIC',
  },
  {
    id: 'rain_splash',
    name: 'RAIN SPLASH',
    desc: 'Impacto de gota d\'água dispersando gotas e moedas.',
    price: 800,
    unlocked: false,
    type: 'splash',
    rarity: 'EPIC',
  },
  {
    id: 'lightning_burst',
    name: 'LIGHTNING BURST',
    desc: 'Explosão bioelétrica com descargas de raios.',
    price: 1200,
    unlocked: false,
    type: 'lightning',
    rarity: 'LEGENDARY',
  },
  {
    id: 'star_burst',
    name: 'STAR BURST',
    desc: 'Supernova estelar com chuveiro de poeira cósmica.',
    price: 1500,
    unlocked: false,
    type: 'explosion',
    rarity: 'LEGENDARY',
  },
  {
    id: 'death_explosion',
    name: 'EXPLOSÃO NEON',
    desc: 'Explosão radiante.',
    price: 0,
    unlocked: true,
    type: 'explosion',
    rarity: 'COMMON',
  },
  {
    id: 'death_glitch',
    name: 'COLAPSO GLITCH',
    desc: 'Distorção de tela.',
    price: 400,
    unlocked: false,
    type: 'glitch',
    rarity: 'RARE',
  },
  {
    id: 'death_pixels',
    name: 'DESINTEGRAÇÃO PIXEL',
    desc: 'O personagem se divide em pequenos blocos de luz.',
    price: 700,
    unlocked: false,
    type: 'pixels',
    rarity: 'EPIC',
  },
  {
    id: 'death_smoke',
    name: 'NÉVOA FANTASMA',
    desc: 'Efeito suave de fumaça evaporante.',
    price: 1000,
    unlocked: false,
    type: 'smoke',
  },
  {
    id: 'death_vanish',
    name: 'IMPLOSÃO VÁCUO',
    desc: 'Colapso instantâneo para um ponto focal.',
    price: 1500,
    unlocked: false,
    type: 'vanish',
  },
  // 7 Novos Efeitos de Morte Épicos
  {
    id: 'death_supernova',
    name: 'SUPERNOVA CÓSMICA',
    desc: 'Detonação estelar que ilumina todo o corredor com poeira dourada.',
    price: 1800,
    unlocked: false,
    type: 'explosion',
    rarity: 'LEGENDARY',
  },
  {
    id: 'death_plasmastorm',
    name: 'TEMPESTADE DE PLASMA',
    desc: 'Arcos de alta voltagem que eletrocutam a parede do abismo.',
    price: 2000,
    unlocked: false,
    type: 'lightning',
    rarity: 'LEGENDARY',
  },
  {
    id: 'death_matrix',
    name: 'DISSOLUÇÃO MATRIX',
    desc: 'Desintegração em cascata de código hexadecimal verde.',
    price: 2200,
    unlocked: false,
    type: 'glitch',
    rarity: 'LEGENDARY',
  },
  {
    id: 'death_prism',
    name: 'ESTILHAÇO PRISMÁTICO',
    desc: 'Fragmentação em milhares de cristais coloridos refratantes.',
    price: 2400,
    unlocked: false,
    type: 'shatter',
    rarity: 'LEGENDARY',
  },
  {
    id: 'death_firestorm',
    name: 'ERUPÇÃO SOLAR',
    desc: 'Coluna de fogo e magma que engole o ponto de colisão.',
    price: 2600,
    unlocked: false,
    type: 'explosion',
    rarity: 'LEGENDARY',
  },
  {
    id: 'death_biohazard',
    name: 'FISSÃO BIO',
    desc: 'Nuvem de partículas atômicas verdes que flutuam na tela.',
    price: 2800,
    unlocked: false,
    type: 'splash',
    rarity: 'LEGENDARY',
  },
  {
    id: 'death_infinitygold',
    name: 'CHUVA DE TESOURO',
    desc: 'Chuva de coroas e moedas douradas no momento do impacto.',
    price: 3500,
    unlocked: false,
    type: 'explosion',
    rarity: 'LEGENDARY',
  },
];

export const INITIAL_THEMES: GameTheme[] = [
  {
    id: 'neon',
    name: 'NEON',
    desc: 'Ciberespaço futurista com paredes de neon e tom escuro.',
    price: 0,
    unlocked: true,
    bgGradient: ['#090912', '#120d26'],
    wallColor: '#3b0764',
    wallGlow: '#a855f7',
    obstacleColor: '#ec4899',
    accentColor: '#22d3ee',
  },
  {
    id: 'tempestade',
    name: 'TEMPESTADE',
    desc: 'Ambiente tempestuoso com relâmpagos sombrios e azul ardósia.',
    price: 300,
    unlocked: false,
    bgGradient: ['#050d1a', '#0a192f'],
    wallColor: '#0f2b48',
    wallGlow: '#0284c7',
    obstacleColor: '#38bdf8',
    accentColor: '#e0f2fe',
  },
  {
    id: 'espaco',
    name: 'ESPAÇO',
    desc: 'Vazio galáctico profundo com paredes roxas estelares.',
    price: 400,
    unlocked: false,
    bgGradient: ['#030014', '#0d001a'],
    wallColor: '#2e1065',
    wallGlow: '#8b5cf6',
    obstacleColor: '#f43f5e',
    accentColor: '#fde047',
  },
  {
    id: 'gelo',
    name: 'GELO',
    desc: 'Abismo congelado polar com brilho de aurora boreal.',
    price: 400,
    unlocked: false,
    bgGradient: ['#02131e', '#072436'],
    wallColor: '#0e4a66',
    wallGlow: '#06b6d4',
    obstacleColor: '#22d3ee',
    accentColor: '#ffffff',
  },
];

export const INITIAL_ACHIEVEMENTS: AchievementItem[] = [
  {
    id: 'ach_first_drop',
    title: 'PRIMEIRA QUEDA',
    desc: 'Jogue sua primeira partida no Wall Drop.',
    type: 'games',
    target: 1,
    progress: 0,
    completed: false,
    rewardText: '+20 Moedas',
    rewardType: 'coins',
    rewardValue: 20,
  },
  {
    id: 'ach_survivor',
    title: 'SOBREVIVENTE',
    desc: 'Alcance 100 pontos em uma partida.',
    type: 'score',
    target: 100,
    progress: 0,
    completed: false,
    rewardText: '+50 Moedas',
    rewardType: 'coins',
    rewardValue: 50,
  },
  {
    id: 'ach_insane_combo',
    title: 'INSANO',
    desc: 'Faça um Combo x10 durante o jogo.',
    type: 'combo',
    target: 10,
    progress: 0,
    completed: false,
    rewardText: '+75 Moedas',
    rewardType: 'coins',
    rewardValue: 75,
  },
  {
    id: 'ach_monster_combo',
    title: 'MONSTRO',
    desc: 'Faça um Combo x25 em uma partida.',
    type: 'combo',
    target: 25,
    progress: 0,
    completed: false,
    rewardText: '+150 Moedas',
    rewardType: 'coins',
    rewardValue: 150,
  },
  {
    id: 'ach_collector',
    title: 'COLECIONADOR',
    desc: 'Colete 500 moedas no total acumulado.',
    type: 'coins',
    target: 500,
    progress: 0,
    completed: false,
    rewardText: '+200 Moedas',
    rewardType: 'coins',
    rewardValue: 200,
  },
  {
    id: 'ach_legendary',
    title: 'LENDÁRIO',
    desc: 'Alcance 1.000 pontos ou Combo x30 no jogo.',
    type: 'score',
    target: 1000,
    progress: 0,
    completed: false,
    rewardText: 'Desbloqueia MYSTERY!',
    rewardType: 'character',
    rewardValue: 'mystery',
  },
  {
    id: 'ach_fearless',
    title: 'SEM MEDO',
    desc: 'Jogue 50 partidas.',
    type: 'games',
    target: 50,
    progress: 0,
    completed: false,
    rewardText: '+300 Moedas',
    rewardType: 'coins',
    rewardValue: 300,
  },
  {
    id: 'ach_stubborn_supreme',
    title: 'TEIMOSO(A) SUPREMO(A)',
    desc: 'Perdeu 20 vezes seguidas sem desistir. Isso é dedicação ou teimosia? As duas coisas.',
    type: 'session_deaths',
    target: 20,
    progress: 0,
    completed: false,
    rewardText: '+150 Moedas 🏆',
    rewardType: 'coins',
    rewardValue: 150,
    isSpecialViral: true,
  },
  // 7 Novas Conquistas Viciantes
  {
    id: 'ach_frenzy_master',
    title: 'MESTRE DO FRENESI',
    desc: 'Ative o modo Frenesi Overdrive 5 vezes com combos épicos.',
    type: 'combo',
    target: 15,
    progress: 0,
    completed: false,
    rewardText: '+250 Moedas 🔥',
    rewardType: 'coins',
    rewardValue: 250,
  },
  {
    id: 'ach_near_miss_god',
    title: 'POR UM FIAPO',
    desc: 'Execute 15 desvios de raspão extremo a menos de 10px das paredes.',
    type: 'score',
    target: 150,
    progress: 0,
    completed: false,
    rewardText: '+300 Moedas ⚡',
    rewardType: 'coins',
    rewardValue: 300,
  },
  {
    id: 'ach_speed_demon',
    title: 'DEMÔNIO DA VELOCIDADE',
    desc: 'Sobreviva na Zona de Hipervelocidade acima de 300 pontos.',
    type: 'score',
    target: 300,
    progress: 0,
    completed: false,
    rewardText: '+400 Moedas 🚀',
    rewardType: 'coins',
    rewardValue: 400,
  },
  {
    id: 'ach_gold_rush',
    title: 'MAGNATA DOURADO',
    desc: 'Colete 100 moedas em uma única corrida frenética.',
    type: 'coins',
    target: 100,
    progress: 0,
    completed: false,
    rewardText: '+350 Moedas 💰',
    rewardType: 'coins',
    rewardValue: 350,
  },
  {
    id: 'ach_instant_revenge',
    title: 'SEDE DE VITÓRIA',
    desc: 'Jogue 100 partidas no total provando sua garra inabalável.',
    type: 'games',
    target: 100,
    progress: 0,
    completed: false,
    rewardText: '+500 Moedas 👑',
    rewardType: 'coins',
    rewardValue: 500,
  },
  {
    id: 'ach_wall_bouncer',
    title: 'MESTRE DAS PAREDES',
    desc: 'Faça um Combo x50 inacreditável com reflexos cósmicos.',
    type: 'combo',
    target: 50,
    progress: 0,
    completed: false,
    rewardText: '+600 Moedas 🌀',
    rewardType: 'coins',
    rewardValue: 600,
  },
  {
    id: 'ach_immortal_drop',
    title: 'GOTA IMORTAL',
    desc: 'Atinja a marca lendária de 500 pontos em uma corrida gloriosa.',
    type: 'score',
    target: 500,
    progress: 0,
    completed: false,
    rewardText: '+1.000 Moedas 🌟',
    rewardType: 'coins',
    rewardValue: 1000,
  },
];

export const generateDailyMissions = (): DailyMission[] => {
  return [
    {
      id: 'mission_coins',
      title: 'COLETE MOEDAS',
      desc: 'Colete 30 moedas durante as partidas de hoje.',
      type: 'coins',
      target: 30,
      progress: 0,
      completed: false,
      claimed: false,
      rewardCoins: 35,
    },
    {
      id: 'mission_score',
      title: 'MANDOU BEM',
      desc: 'Alcance 100 pontos em uma partida.',
      type: 'score',
      target: 100,
      progress: 0,
      completed: false,
      claimed: false,
      rewardCoins: 50,
    },
    {
      id: 'mission_combo',
      title: 'COMBO MÁXIMO',
      desc: 'Faça um Combo x10.',
      type: 'combo',
      target: 10,
      progress: 0,
      completed: false,
      claimed: false,
      rewardCoins: 40,
    },
    // 4 Novas Missões Diárias Viciantes
    {
      id: 'mission_frenzy',
      title: 'FRENESI NEON',
      desc: 'Acumule 50 moedas raras ou combos hoje.',
      type: 'coins',
      target: 50,
      progress: 0,
      completed: false,
      claimed: false,
      rewardCoins: 60,
    },
    {
      id: 'mission_high_streak',
      title: 'REFLEXO DE AÇO',
      desc: 'Faça um Combo x15 em qualquer corrida.',
      type: 'combo',
      target: 15,
      progress: 0,
      completed: false,
      claimed: false,
      rewardCoins: 75,
    },
    {
      id: 'mission_marathon',
      title: 'MARATONA DE QUEDAS',
      desc: 'Jogue 10 partidas no dia.',
      type: 'games',
      target: 10,
      progress: 0,
      completed: false,
      claimed: false,
      rewardCoins: 80,
    },
    {
      id: 'mission_hyper_score',
      title: 'REI DO ABISMO',
      desc: 'Alcance 200 pontos em uma única descida.',
      type: 'score',
      target: 200,
      progress: 0,
      completed: false,
      claimed: false,
      rewardCoins: 100,
    },
  ];
};

export const FUNNY_EXCUSES_BY_LANG: Record<string, string[]> = {
  pt: [
    'Foi de Wall.',
    'A parede ganhou.',
    'Tu nem tentou.',
    'Isso foi pessoal.',
    '💀',
    'Quase... muito quase.',
    'A parede está rindo.',
    'Como é que conseguiste?',
    'Nem a parede esperava isso.',
    'Mais uma. Eu sei que vais.',
    'Recorde mundial de derrota.',
    'F.',
    'Bateu bonito!',
    'A gravidade não perdoa.',
    'A parede nem piscou.',
    'Erro de cálculo brutal.',
    'Poderia ter sido pior... ou não.',
    'A parede mandou abraço.',
    'Sua habilidade tirou folga.',
    'Isso vai pro TikTok.',
    'Desligaram seu reflexo?',
    'A parede deu 10/10 na nota.',
    'Acontece nas melhores famílias.',
    'Tática ousada, pena que errou.',
    'Fez a parede sentir nada.',
    'O vício te chama de volta.',
    'Pausa dramática...',
    'Na próxima vai! (Talvez)',
    'Pro player em dia ruim.',
    'O chão sorriu para você.',
    'Colisão perfeita!',
    'A parede segue invicta.',
    'Foi de berço.',
    'Instinto superior falhou!',
    'Calma, respira, clica de novo.',
    'Errou o timing por 1 milissegundo.',
    'Parede 1 x 0 Você.',
    'Foi só um teste... né?',
    'Até a física chorou.',
    'Foi de F com estilo!',
  ],
  en: [
    'Wall won.',
    'That was personal.',
    '💀',
    'So close... almost.',
    'The wall is laughing at you.',
    'How did you manage that?',
    'Even the wall didn\'t expect that.',
    'One more. I know you will.',
    'World record defeat.',
    'F.',
    'The wall didn\'t even blink.',
    'Physics sent regards.',
  ],
  es: [
    'Fue de Wall.',
    'Ganó la pared.',
    'Ni lo intentaste.',
    'Eso fue personal.',
    '💀',
    'Casi... muy cerca.',
    'La pared se está riendo.',
    '¿Cómo lo lograste?',
    'Ni la pared se lo esperaba.',
    'Una más. Sé que vas a jugar.',
    'Récord mundial de derrota.',
    'F.',
  ],
  fr: [
    'Wall a gagné.',
    'C\'était personnel.',
    '💀',
    'Presque... trop près.',
    'Le mur rigole.',
    'F.',
  ],
  de: [
    'Die Wand hat gewonnen.',
    '💀',
    'Fast... wirklich fast.',
    'F.',
  ],
  it: [
    'Il muro ha vinto.',
    '💀',
    'F.',
  ],
  ja: [
    '壁の勝ち。',
    '💀',
    'F.',
  ],
};

export const HIGH_SCORE_MEME_PHRASES: Record<string, string[]> = {
  pt: [
    'Agora tenta superar.',
    'Isso foi absurdo.',
    'Tu realmente conseguiste.',
    'A parede ficou preocupada.',
    'Nível lendário ativado!',
    'A parede tremeu!',
  ],
  en: [
    'Now try to beat this.',
    'That was absurd.',
    'You actually did it.',
    'The wall got worried.',
  ],
  es: [
    'Ahora intenta superarlo.',
    'Eso fue absurdo.',
    'Realmente lo lograste.',
    'La parede se preocupó.',
  ],
};

export const ARROGANT_NARRATOR_PHRASES: Record<string, Record<string, string[]>> = {
  pt: {
    welcome: [
      'Bem-vindo ao WALL DROP, {name}. Vamos descobrir até onde consegues chegar.',
    ],
    start: [
      'Vamos, {name}!',
      'Manda ver, {name}!',
      'Foco, {name}!',
      'Até onde consegues chegar, {name}?',
      'Agora é a tua vez, {name}!',
      'Mais uma, {name}!',
    ],
    defeat: [
      'Quase, {name}. Tenta novamente.',
      'Não desistes, {name}!',
      'Excelente partida, {name}.',
      'Foi por pouco!',
      'Mais uma, {name}!',
    ],
    comboBreak: [
      'Perdeu o combo!',
      'Perdeu o foco, {name}!',
    ],
    combo3: ['Boa, {name}!', 'Isso!', 'Continua!', '3 seguidas no ritmo!'],
    combo5: [
      'Perfeito!',
      'Sensacional!',
      'Que sequência absurda!',
      '5 seguidas! Você tá voando!',
      'Ritmo impecável, {name}!',
    ],
    combo10: [
      'Impressionante, {name}!',
      'Está imparável!',
      'Está imparável, {name}!',
      'Que sequência absurda!',
      '10 SEGUIDAS! MODO DEMÔNIO!',
      'Reflexos sobre-humanos!',
      'Ninguém te para agora!',
    ],
    comboMilestone: [
      'Que sequência absurda!',
      'Está imparável!',
      'Está imparável, {name}!',
      'Sequência magistral!',
      'Você entrou na zona quântica!',
      'Mestre absoluto dos combos!',
      'Reflexos de puro aço!',
    ],
    evolution: ['Armadilhas evoluíram!', 'Prepara-te, {name}!'],
    highScore: ['Novo recorde, {name}!', 'Impressionante, {name}!', 'Incrível!'],
    nearMiss: ['Quase!', 'Raspou!', 'Foi por um fiapo!'],
    coinMilestone: ['Chuva de moedas!', 'Boa!'],
    unlock: ['Desbloqueado!', 'Novo item, {name}!'],
  },
  en: {
    welcome: [
      'Welcome to WALL DROP, {name}. Let\'s see how far you can go.',
    ],
    start: [
      'Let\'s go, {name}!',
      'Show us what you got, {name}!',
      'Focus, {name}!',
      'Your turn, {name}!',
      'One more, {name}!',
    ],
    defeat: [
      'Almost, {name}. Try again.',
      'Don\'t give up, {name}!',
      'Great match, {name}.',
      'So close!',
    ],
    comboBreak: [
      'Combo dropped!',
      'Lost focus, {name}!',
    ],
    combo3: ['Nice, {name}!', 'Keep it up!'],
    combo5: ['Awesome!', 'Perfect!', 'What an insane streak!'],
    combo10: ['Unstoppable, {name}!', 'You are unstoppable!', 'What an absurd combo streak!', 'Godlike reflexes!'],
    comboMilestone: ['Unstoppable streak!', 'Insane combo!', 'You are untouchable, {name}!'],
    evolution: ['Traps evolved!', 'Get ready, {name}!'],
    highScore: ['New record, {name}!', 'Impressive, {name}!'],
    nearMiss: ['So close!', 'Pure luck!'],
    coinMilestone: ['Coin shower!', 'Nice!'],
    unlock: ['Unlocked!', 'New item, {name}!'],
  },
  es: {
    welcome: [
      'Bienvenido a WALL DROP, {name}. Veamos qué tan lejos puedes llegar.',
    ],
    start: [
      '¡Vamos, {name}!',
      '¡Demuestra tu nivel, {name}!',
      '¡Enfócate, {name}!',
      '¡Tu turno, {name}!',
      '¡Una más, {name}!',
    ],
    defeat: [
      'Casi, {name}. Intenta de nuevo.',
      '¡No te rindas, {name}!',
      'Excelente partida, {name}.',
      '¡Por muy poco!',
    ],
    comboBreak: [
      '¡Perdiste el combo!',
      '¡Concentración, {name}!',
    ],
    combo3: ['¡Buena, {name}!', '¡Sigue así!'],
    combo5: ['¡Perfecto!', '¡Increíble!', '¡Qué racha tan absurda!'],
    combo10: ['¡Imparable, {name}!', '¡Estás imparable!', '¡Qué racha absurda!', '¡Reflejos divinos!'],
    comboMilestone: ['¡Racha imparable!', '¡Increíble secuencia!', '¡Estás en la zona, {name}!'],
    evolution: ['¡Trampas evolucionadas!'],
    highScore: ['¡Nuevo récord, {name}!', '¡Impresionante, {name}!'],
    nearMiss: ['¡Por un pelo!', '¡Cerca!'],
    coinMilestone: ['¡Lluvia de monedas!', '¡Bien!'],
    unlock: ['¡Desbloqueado!', '¡Nuevo objeto, {name}!'],
  },
  fr: {
    welcome: [
      'Bienvenue dans WALL DROP, {name}. Voyons jusqu\'où tu peux aller.',
    ],
    start: [
      'Allez, {name}!',
      'À toi de jouer, {name}!',
      'Concentration, {name}!',
    ],
    defeat: [
      'Presque, {name}. Réessaye.',
      'Ne baisse pas les bras, {name}!',
      'Excellente partie, {name}.',
    ],
    comboBreak: [
      'Combo perdu!',
    ],
    combo3: ['Bien, {name}!', 'Continue!'],
    combo5: ['Parfait!', 'Génial!'],
    combo10: ['Imparable, {name}!', 'Impressionnant!'],
    evolution: ['Pièges évolués!'],
    highScore: ['Nouveau record, {name}!'],
    nearMiss: ['Tout près!'],
    coinMilestone: ['Pluie de pièces!'],
    unlock: ['Débloqué!'],
  },
  de: {
    welcome: [
      'Willkommen bei WALL DROP, {name}. Mal sehen wie weit du kommst.',
    ],
    start: [
      'Los geht\'s, {name}!',
      'Fokus, {name}!',
      'Du bist dran, {name}!',
    ],
    defeat: [
      'Fast, {name}. Versuch es nochmal.',
      'Nicht aufgeben, {name}!',
      'Gute Runde, {name}.',
    ],
    comboBreak: [
      'Combo verloren!',
    ],
    combo3: ['Gut, {name}!', 'Weiter so!'],
    combo5: ['Perfekt!', 'Wahnsinn!'],
    combo10: ['Unaufhaltsam, {name}!'],
    evolution: ['Fallen evolviert!'],
    highScore: ['Neuer Rekord, {name}!'],
    nearMiss: ['Haarscharf!'],
    coinMilestone: ['Münzen-Regen!'],
    unlock: ['Freigeschaltet!'],
  },
  it: {
    welcome: [
      'Benvenuto su WALL DROP, {name}. Vediamo dove riesci ad arrivare.',
    ],
    start: [
      'Andiamo, {name}!',
      'Concentrazione, {name}!',
      'Tocca a te, {name}!',
    ],
    defeat: [
      'Quasi, {name}. Riprova.',
      'Non mollare, {name}!',
      'Ottima partita, {name}.',
    ],
    comboBreak: [
      'Combo perso!',
    ],
    combo3: ['Bravo, {name}!', 'Continua così!'],
    combo5: ['Perfetto!', 'Fantastico!'],
    combo10: ['Imparabile, {name}!'],
    evolution: ['Trappole evolute!'],
    highScore: ['Nuovo record, {name}!'],
    nearMiss: ['Per un pelo!'],
    coinMilestone: ['Pioggia di monete!'],
    unlock: ['Sbloccato!'],
  },
  ja: {
    welcome: ['WALL DROPへようこそ、{name}さん。どこまで行けるか試してみよう。'],
    start: ['行くぞ、{name}！', '集中しろ、{name}！'],
    defeat: ['惜しかった、{name}。もう一度挑戦しよう。', 'あきらめるな、{name}！'],
    comboBreak: ['コンボが途切れた！'],
    combo3: ['ナイス、{name}！'],
    combo5: ['パーフェクト！'],
    combo10: ['アンストッパブル！'],
    evolution: ['トラップ進化！'],
    highScore: ['新記録達成、{name}！'],
    nearMiss: ['危なかった！'],
    coinMilestone: ['コインラッシュ！'],
    unlock: ['解放完了！'],
  },
  zh: {
    welcome: ['欢迎来到 WALL DROP，{name}。让我们看看你能走到哪一步。'],
    start: ['加油，{name}！', '看你的了，{name}！'],
    defeat: ['就差一点，{name}。再试一次吧。', '别放弃，{name}！'],
    comboBreak: ['连击中断！'],
    combo3: ['漂亮，{name}！'],
    combo5: ['完美！'],
    combo10: ['无人能挡！'],
    evolution: ['陷阱升级！'],
    highScore: ['刷新新纪录，{name}！'],
    nearMiss: ['好险！'],
    coinMilestone: ['金币雨！'],
    unlock: ['已解锁！'],
  },
};

export const NARRATOR_PHRASES = ARROGANT_NARRATOR_PHRASES.pt;

export const DEFAULT_SETTINGS: GameSettings = {
  musicVolume: 0.5,
  sfxVolume: 0.8,
  narratorEnabled: true,
  narratorVolume: 0.9,
  narratorSpeed: NARRATOR_SPEED,
  narratorVoiceGender: 'male',
  vibrationEnabled: true,
  language: 'pt',
  playerName: '',
  firstLaunchDone: false,
};

export const DEFAULT_STATS: GameStats = {
  totalGames: 0,
  totalCoinsCollected: 0,
  highestCombo: 0,
  bestScore: 0,
};

export const DEFAULT_CUSTOM_CHARACTER: CustomCharacterConfig = {
  enabled: false,
  primaryColor: '#00f2ff',
  glowColor: '#06b6d4',
  accentColor: '#38bdf8',
  trailColor: 'rgba(0, 242, 255, 0.7)',
  eyeColor: '#ffffff',
  particleType: 'cyan_glow',
  accessory: 'crown',
  auraEffect: 'cosmic_rings',
  unlockedColorPalettes: ['palette_default_cyan'],
  unlockedParticleStyles: ['cyan_glow'],
  unlockedAccessories: ['acc_none', 'acc_crown', 'acc_wings', 'acc_horns', 'acc_halo', 'acc_visor'],
  unlockedAuras: ['aura_none', 'aura_cosmic_rings', 'aura_solar_flame', 'aura_quantum_storm', 'aura_crystal_frost', 'aura_diamond_prism'],
};

export const CUSTOM_ACCESSORIES: CustomAccessoryItem[] = [
  {
    id: 'acc_none',
    accessoryType: 'none',
    name: 'Sem Adorno',
    desc: 'Visual limpo e aerodinâmico sem itens equipados.',
    price: 0,
    icon: 'Sparkles',
    rarity: 'COMMON',
  },
  {
    id: 'acc_crown',
    accessoryType: 'crown',
    name: '👑 Coroa Imperial Flutuante',
    desc: 'Coroa de ouro puro esculpida com gemas celestes que flutua acima da cabeça.',
    price: 0,
    icon: 'Crown',
    rarity: 'LEGENDARY',
  },
  {
    id: 'acc_wings',
    accessoryType: 'wings',
    name: '🪽 Asas Cósmicas de Plasma',
    desc: 'Asas de energia cibernética que batem e ondulam no ritmo da descida.',
    price: 0,
    icon: 'Flame',
    rarity: 'LEGENDARY',
  },
  {
    id: 'acc_horns',
    accessoryType: 'horns',
    name: '⚡ Chifres Cibernéticos Neon',
    desc: 'Chifres de titânio futuristas com pontas de plasma incandescente.',
    price: 0,
    icon: 'Zap',
    rarity: 'EPIC',
  },
  {
    id: 'acc_halo',
    accessoryType: 'halo',
    name: '😇 Halo Sagrado Celestial',
    desc: 'Anel místico de luz dourada divina que gira e emite faíscas sagradas.',
    price: 0,
    icon: 'Sun',
    rarity: 'EPIC',
  },
  {
    id: 'acc_visor',
    accessoryType: 'visor',
    name: '🕶️ Visor Holográfico Cyberpunk',
    desc: 'Óculos cibernéticos com display HUD de laser e reflexo dinâmico.',
    price: 0,
    icon: 'Eye',
    rarity: 'RARE',
  },
];

export const CUSTOM_AURAS: CustomAuraItem[] = [
  {
    id: 'aura_none',
    auraType: 'none',
    name: 'Sem Aura',
    desc: 'Aura padrão básica sem efeitos orbitais.',
    price: 0,
    icon: 'Sparkles',
    rarity: 'COMMON',
  },
  {
    id: 'aura_cosmic_rings',
    auraType: 'cosmic_rings',
    name: '🪐 Halos Orbitais de Fótons',
    desc: '3 anéis de plasma cósmico girando em órbita elíptica 3D ao redor do personagem.',
    price: 0,
    icon: 'Layers',
    rarity: 'LEGENDARY',
  },
  {
    id: 'aura_solar_flame',
    auraType: 'solar_flame',
    name: '🔥 Chamas Solares de Fusão',
    desc: 'Labaredas pulsantes de plasma termonuclear com faíscas incandescentes.',
    price: 0,
    icon: 'Flame',
    rarity: 'LEGENDARY',
  },
  {
    id: 'aura_quantum_storm',
    auraType: 'quantum_storm',
    name: '⚡ Tempestade Quântica 1M Volts',
    desc: 'Arcos elétricos reluzentes estalando e orbitando o núcleo em alta velocidade.',
    price: 0,
    icon: 'Zap',
    rarity: 'EPIC',
  },
  {
    id: 'aura_crystal_frost',
    auraType: 'crystal_frost',
    name: '❄️ Escudo Glacial de Cristal',
    desc: 'Fragmentos de gelo estelar e cristais giratórios com brilho ártico.',
    price: 0,
    icon: 'Shield',
    rarity: 'EPIC',
  },
  {
    id: 'aura_diamond_prism',
    auraType: 'diamond_prism',
    name: '💎 Prisma Hiper-Dimensional',
    desc: 'Feixes de luz refratada em arco-íris cósmico com poeira de diamante.',
    price: 0,
    icon: 'Gem',
    rarity: 'LEGENDARY',
  },
];

export const DEFAULT_CUSTOM_THEME: CustomThemeConfig = {
  enabled: false,
  bgGradient: ['#020617', '#0f172a'],
  wallColor: '#1e293b',
  wallGlow: '#00f2ff',
  obstacleColor: '#00f2ff',
  accentColor: '#38bdf8',
  gridStyle: 'cyber_grid',
  unlockedBackgrounds: ['bg_matrix_cyber'],
};

export const DEFAULT_PLAYER_UPGRADES: PlayerUpgrades = {
  trailIntensity: 0,
  glowIntensity: 0,
  trailLength: 0,
  jellyPulse: 0,
  orbitalSparks: 0,
  coinMagnet: 0,
  shieldStart: 0,
  nearMissBonus: 0,
  slowMoMastery: 0,
  goldRush: 0,
};

export const CUSTOM_PALETTES: CustomPaletteItem[] = [
  // --- INICIAL (0 Moedas) ---
  {
    id: 'palette_default_cyan',
    name: 'Ciano Hiper-Neon',
    desc: 'Visual clássico cibernético com energia de plasma ciano brilhante.',
    price: 0,
    primaryColor: '#00f2ff',
    glowColor: '#06b6d4',
    accentColor: '#ffffff',
    trailColor: 'rgba(0, 242, 255, 0.8)',
    particleType: 'cyan_glow',
    rarity: 'COMMON',
  },
  // --- CUSTOMIZAÇÕES VIP (2.000 Moedas Cada) ---
  {
    id: 'palette_slate_shadow',
    name: 'Ardósia Noturna',
    desc: 'Monocromático elegante com reflexos em prata e cinza espacial.',
    price: 2000,
    primaryColor: '#94a3b8',
    glowColor: '#64748b',
    accentColor: '#f8fafc',
    trailColor: 'rgba(148, 163, 184, 0.75)',
    particleType: 'void_shadow',
    rarity: 'RARE',
  },
  {
    id: 'palette_radioactive_emerald',
    name: 'Esmeralda Bio-Plasma',
    desc: 'Plasma biológico instável com brilho verde neon radioativo.',
    price: 2000,
    primaryColor: '#10b981',
    glowColor: '#059669',
    accentColor: '#a7f3d0',
    trailColor: 'rgba(16, 185, 129, 0.85)',
    particleType: 'toxic_plasma',
    rarity: 'RARE',
  },
  {
    id: 'palette_arctic_frost',
    name: 'Aurora Glacial Criogênica',
    desc: 'Núcleo de gelo puro envolto em ventos árticos cristalinos.',
    price: 2000,
    primaryColor: '#38bdf8',
    glowColor: '#0284c7',
    accentColor: '#e0f2fe',
    trailColor: 'rgba(56, 189, 248, 0.85)',
    particleType: 'ice',
    rarity: 'RARE',
  },
  {
    id: 'palette_abyssal_void',
    name: 'Vórtice Abissal Cósmico',
    desc: 'Aura roxa impenetrável de matéria escura distorcendo a gravidade.',
    price: 2000,
    primaryColor: '#8b5cf6',
    glowColor: '#7c3aed',
    accentColor: '#e9d5ff',
    trailColor: 'rgba(139, 92, 246, 0.9)',
    particleType: 'void_shadow',
    rarity: 'EPIC',
  },
  {
    id: 'palette_quantum_pink',
    name: 'Sakura Quântico Neon',
    desc: 'Radiação rosa estelar com rastro fluido de partículas cósmicas.',
    price: 2000,
    primaryColor: '#f472b6',
    glowColor: '#ec4899',
    accentColor: '#fdf2f8',
    trailColor: 'rgba(244, 114, 182, 0.9)',
    particleType: 'stardust',
    rarity: 'EPIC',
  },
  {
    id: 'palette_electric_storm',
    name: 'Tempestade de Raios 1M Volts',
    desc: 'Arco de alta voltagem que projeta faíscas contínuas em alta velocidade.',
    price: 2000,
    primaryColor: '#38bdf8',
    glowColor: '#eab308',
    accentColor: '#ffffff',
    trailColor: 'rgba(56, 189, 248, 0.9)',
    particleType: 'electric',
    rarity: 'EPIC',
  },
  {
    id: 'palette_pure_gold_royale',
    name: 'Ouro Imperial Royale',
    desc: 'Ouro celestial esculpido à mão com faíscas douradas soberanas.',
    price: 2000,
    primaryColor: '#fbbf24',
    glowColor: '#d97706',
    accentColor: '#fffbeb',
    trailColor: 'rgba(251, 191, 36, 0.95)',
    particleType: 'stardust',
    rarity: 'LEGENDARY',
  },
  {
    id: 'palette_infernal_magma',
    name: 'Magma Vulcânico Solar',
    desc: 'Núcleo incandescente de lava ardente a mais de 3000°C.',
    price: 2000,
    primaryColor: '#ff4500',
    glowColor: '#dc2626',
    accentColor: '#fef08a',
    trailColor: 'rgba(255, 69, 0, 0.95)',
    particleType: 'fire',
    rarity: 'LEGENDARY',
  },
  {
    id: 'palette_glitch_matrix',
    name: 'Matrix Sobrecarga Cromática',
    desc: 'Pixels corrompidos em overdrive que rasgam o tecido da simulação.',
    price: 2000,
    primaryColor: '#22c55e',
    glowColor: '#f43f5e',
    accentColor: '#00f2ff',
    trailColor: 'rgba(34, 197, 94, 0.95)',
    particleType: 'glitch_pixels',
    rarity: 'LEGENDARY',
  },
  {
    id: 'palette_supernova_cosmic',
    name: 'Supernova Cósmica',
    desc: 'Explosão estelar com anéis de luz violeta e partículas hiper-luminosas.',
    price: 2000,
    primaryColor: '#c084fc',
    glowColor: '#ec4899',
    accentColor: '#fef08a',
    trailColor: 'rgba(192, 132, 252, 0.95)',
    particleType: 'stardust',
    rarity: 'LEGENDARY',
  },
  {
    id: 'palette_golden_phoenix',
    name: 'Fênix Dourada Flamejante',
    desc: 'Asas de fogo sagrado reluzindo em ouro puro e chamas eternas.',
    price: 2000,
    primaryColor: '#f59e0b',
    glowColor: '#ef4444',
    accentColor: '#fef3c7',
    trailColor: 'rgba(245, 158, 11, 0.95)',
    particleType: 'fire',
    rarity: 'LEGENDARY',
  },
  {
    id: 'palette_quantum_rift',
    name: 'Fenda Dimensional',
    desc: 'Anomalia espacial com distorção gravitacional e arcos de antimatéria.',
    price: 2000,
    primaryColor: '#06b6d4',
    glowColor: '#8b5cf6',
    accentColor: '#ffffff',
    trailColor: 'rgba(6, 182, 212, 0.95)',
    particleType: 'electric',
    rarity: 'LEGENDARY',
  },
];

export const CUSTOM_BACKGROUNDS: CustomBackgroundItem[] = [
  // --- INICIAL (0 Moedas) ---
  {
    id: 'bg_matrix_cyber',
    name: 'Arena Cyber Matrix',
    desc: 'Grade digital padrão com reflexos em ciano e azul escuro.',
    price: 0,
    bgGradient: ['#020617', '#0f172a'],
    wallColor: '#1e293b',
    wallGlow: '#00f2ff',
    obstacleColor: '#00f2ff',
    accentColor: '#38bdf8',
    gridStyle: 'cyber_grid',
    rarity: 'COMMON',
  },
  // --- CUSTOMIZAÇÕES VIP DE CENÁRIO (2.000 Moedas Cada) ---
  {
    id: 'bg_deep_ocean',
    name: 'Abismo Oceânico Profundo',
    desc: 'Profundezas oceânicas com paredes azul-marinho e bio-luminescência.',
    price: 2000,
    bgGradient: ['#021226', '#031e3d'],
    wallColor: '#0a2e5c',
    wallGlow: '#38bdf8',
    obstacleColor: '#0ea5e9',
    accentColor: '#bae6fd',
    gridStyle: 'matrix_dots',
    rarity: 'RARE',
  },
  {
    id: 'bg_arctic_glacier',
    name: 'Glaciar Ártico Eterno',
    desc: 'Profundezas congeladas com cristais de gelo e reflexos celestes.',
    price: 2000,
    bgGradient: ['#021b2b', '#083344'],
    wallColor: '#164e63',
    wallGlow: '#67e8f9',
    obstacleColor: '#38bdf8',
    accentColor: '#e0f2fe',
    gridStyle: 'matrix_dots',
    rarity: 'RARE',
  },
  {
    id: 'bg_emerald_forest',
    name: 'Caverna Bio-Esmeralda',
    desc: 'Vegetação alienígena fluorescente e paredes de jade pulsante.',
    price: 2000,
    bgGradient: ['#022c22', '#064e3b'],
    wallColor: '#047857',
    wallGlow: '#34d399',
    obstacleColor: '#10b981',
    accentColor: '#a7f3d0',
    gridStyle: 'matrix_dots',
    rarity: 'RARE',
  },
  {
    id: 'bg_synthwave_sunset',
    name: 'Synthwave 80s Retrô',
    desc: 'Pôr do sol retrô com tons saturados de magenta e azul índigo.',
    price: 2000,
    bgGradient: ['#180026', '#311042'],
    wallColor: '#581c87',
    wallGlow: '#f43f5e',
    obstacleColor: '#06b6d4',
    accentColor: '#ec4899',
    gridStyle: 'speed_stripes',
    rarity: 'EPIC',
  },
  {
    id: 'bg_deep_space_nebula',
    name: 'Nebulosa Cósmica Interstelar',
    desc: 'Espaço profundo com nuvens púrpuras e luz estelar infinita.',
    price: 2000,
    bgGradient: ['#0a0017', '#2e0854'],
    wallColor: '#3b0764',
    wallGlow: '#c084fc',
    obstacleColor: '#f472b6',
    accentColor: '#e879f9',
    gridStyle: 'stardust_nebula',
    rarity: 'EPIC',
  },
  {
    id: 'bg_volcanic_inferno',
    name: 'Inferno Magmático Vulcânico',
    desc: 'Poço de magma fervente com paredes de rocha fundida e labaredas.',
    price: 2000,
    bgGradient: ['#1a0500', '#450a0a'],
    wallColor: '#7f1d1d',
    wallGlow: '#f97316',
    obstacleColor: '#ef4444',
    accentColor: '#facc15',
    gridStyle: 'speed_stripes',
    rarity: 'LEGENDARY',
  },
  {
    id: 'bg_golden_vortex',
    name: 'Vórtice Dourado dos Campeões',
    desc: 'Templo supremo com paredes banhadas a ouro e luz mística estelar.',
    price: 2000,
    bgGradient: ['#1c1301', '#451a03'],
    wallColor: '#78350f',
    wallGlow: '#fbbf24',
    obstacleColor: '#f59e0b',
    accentColor: '#fef08a',
    gridStyle: 'cyber_grid',
    rarity: 'LEGENDARY',
  },
];

export const UPGRADE_DEFINITIONS: UpgradeDefinition[] = [
  {
    id: 'trailIntensity',
    name: 'Densidade do Rastro Neon',
    desc: 'Aumenta a taxa de partículas e o brilho da cauda luminosa deixada pela gota.',
    icon: 'Sparkles',
    maxLevel: 5,
    costPerLevel: 300,
    getEffectDesc: (lvl) => lvl === 0 ? 'Padrão (Nível 0)' : `Densidade do Rastro: +${lvl * 25}% partículas e brilho`,
  },
  {
    id: 'glowIntensity',
    name: 'Aura e Potência de Brilho',
    desc: 'Expande o halo de luz neon envolta do personagem iluminando a descida.',
    icon: 'Sun',
    maxLevel: 5,
    costPerLevel: 400,
    getEffectDesc: (lvl) => lvl === 0 ? 'Padrão (Nível 0)' : `Raio de Aura: +${lvl * 6}px e +${lvl * 20}% intensidade`,
  },
  {
    id: 'trailLength',
    name: 'Persistência da Cauda de Luz',
    desc: 'Prolonga o tempo de vida das partículas na tela, criando um rastro longo e contínuo.',
    icon: 'Clock',
    maxLevel: 5,
    costPerLevel: 500,
    getEffectDesc: (lvl) => lvl === 0 ? 'Padrão (Nível 0)' : `Duração do Rastro: +${lvl * 30}% tempo em tela`,
  },
  {
    id: 'jellyPulse',
    name: 'Pulso de Gel & Elasticidade',
    desc: 'Torna a animação orgânica de deformação de gel mais acentuada e fluida ao cair.',
    icon: 'Sliders',
    maxLevel: 5,
    costPerLevel: 600,
    getEffectDesc: (lvl) => lvl === 0 ? 'Padrão (Nível 0)' : `Elasticidade Orgânica: +${lvl * 20}% squash & stretch`,
  },
  {
    id: 'orbitalSparks',
    name: 'Faíscas Orbitais de Energia',
    desc: 'Adiciona pequenas partículas de energia cintilantes girando em órbita contínua.',
    icon: 'Zap',
    maxLevel: 5,
    costPerLevel: 800,
    getEffectDesc: (lvl) => lvl === 0 ? 'Desativado (Nível 0)' : `Órbita Ativa: ${lvl} faíscas estelares girando ao redor`,
  },
];

